language: python
python:
#  - "3.4"
  - "2.7"
  - "2.6"
before_install:
  - sudo apt-get install unixodbc-dev
  - sudo apt-get install libsqliteodbc
  - ls /usr/lib/odbc
  - pip install unittest2
install:
  - pip install -e .
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then python tests2/sqlitetests.py 'Driver=SQLITE3;Database=sqlite.db'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python tests3/sqlitetests.py 'Driver=SQLITE3;Database=sqlite.db'; fi
