sudo: false
addons:
  apt:
    packages:
      - libsqliteodbc
language: python
python:
  - "3.4"
  - "2.7"
  - "2.6"
install: pip install -e .
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then python tests2/sqlitetests.py 'Driver=/usr/lib/x86_64-linux-gnu/odbc/libsqliteodbc.so;Database=sqlite.db'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python tests3/sqlitetests.py 'Driver=/usr/lib/x86_64-linux-gnu/odbc/libsqliteodbc.so;Database=sqlite.db'; fi
